[workspace]
members = [
    "serde",
    "serde_derive",
    "serde_derive_internals",
    "serde_test",
    "test_suite",
]

[patch.crates-io]
libc = { git = "https://github.com/raoulstrackx/libc.git", branch = "raoul/version_0_2_106" }
